
# shttp/parse/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = ')\x92\xd6\xd6](\xb5\x07\xba\xbf\x8eq}\x9f@\xc7'
    
_lr_action_items = {'PROTO':([5,],[10,]),'URL':([3,],[5,]),'HVAL':([6,],[11,]),'HEADER':([4,8,14,],[6,6,-5,]),'CRLF':([1,4,7,8,9,10,11,13,14,],[4,-6,12,-6,-4,-2,14,-3,-5,]),'METHOD':([0,],[3,]),'$end':([2,12,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'headers':([4,8,],[7,13,]),'reqstr':([0,],[1,]),'request':([0,],[2,]),'empty':([4,8,],[9,9,]),'aheader':([4,8,],[8,8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> request","S'",1,None,None,None),
  ('request -> reqstr CRLF headers CRLF','request',4,'p_req','/Users/hansens/shttp/shttp/parse/parserdef.py',6),
  ('reqstr -> METHOD URL PROTO','reqstr',3,'p_reqstr','/Users/hansens/shttp/shttp/parse/parserdef.py',10),
  ('headers -> aheader headers','headers',2,'p_headers','/Users/hansens/shttp/shttp/parse/parserdef.py',18),
  ('headers -> empty','headers',1,'p_headers','/Users/hansens/shttp/shttp/parse/parserdef.py',19),
  ('aheader -> HEADER HVAL CRLF','aheader',3,'p_aheader','/Users/hansens/shttp/shttp/parse/parserdef.py',23),
  ('empty -> <empty>','empty',0,'p_empty','/Users/hansens/shttp/shttp/parse/parserdef.py',27),
]
